import { quranMetaData } from '$data/quranMeta';

const chapterDisplayOverrides = {
	1: { transliteration: 'Al Fatihah', translation: 'Pembukaan' },
	2: { transliteration: 'Al Baqarah', translation: 'Sapi Betina' },
	3: { transliteration: 'Ali Imran', translation: 'Keluarga Imran' },
	4: { transliteration: 'An Nisa', translation: 'Perempuan' },
	5: { transliteration: 'Al Maidah', translation: 'Hidangan' },
	6: { transliteration: 'Al Anam', translation: 'Binatang Ternak' },
	7: { transliteration: 'Al Araf', translation: 'Tempat Tertinggi' },
	8: { transliteration: 'Al Anfal', translation: 'Rampasan Perang' },
	9: { transliteration: 'At Taubah', translation: 'Pengampunan' },
	10: { transliteration: 'Yunus', translation: 'Yunus' },
	11: { transliteration: 'Hud', translation: 'Hud' },
	12: { transliteration: 'Yusuf', translation: 'Yusuf' },
	13: { transliteration: 'Ar Rad', translation: 'Guruh' },
	14: { transliteration: 'Ibrahim', translation: 'Ibrahim' },
	15: { transliteration: 'Al Hijr', translation: 'Hijr' },
	16: { transliteration: 'An Nahl', translation: 'Lebah' },
	17: { transliteration: 'Al Isra', translation: 'Memperjalankan pada Malam Hari' },
	18: { transliteration: 'Al Kahf', translation: 'Gua' },
	19: { transliteration: 'Maryam', translation: 'Maryam' },
	20: { transliteration: 'Ta Ha', translation: 'Ta Ha' },
	21: { transliteration: 'Al Anbiya', translation: 'Para Nabi' },
	22: { transliteration: 'Al Hajj', translation: 'Haji' },
	23: { transliteration: 'Al Muminun', translation: 'Orang-Orang Mukmin' },
	24: { transliteration: 'An Nur', translation: 'Cahaya' },
	25: { transliteration: 'Al Furqan', translation: 'Pembeda' },
	26: { transliteration: 'Asy Syuara', translation: 'Para Penyair' },
	27: { transliteration: 'An Naml', translation: 'Semut' },
	28: { transliteration: 'Al Qasas', translation: 'Kisah-Kisah' },
	29: { transliteration: 'Al Ankabut', translation: 'Laba-Laba' },
	30: { transliteration: 'Ar Rum', translation: 'Romawi' },
	31: { transliteration: 'Luqman', translation: 'Luqman' },
	32: { transliteration: 'As Sajdah', translation: 'Sajdah' },
	33: { transliteration: 'Al Ahzab', translation: 'Golongan-Golongan yang Bersekutu' },
	34: { transliteration: 'Saba', translation: 'Saba' },
	35: { transliteration: 'Fatir', translation: 'Pencipta' },
	36: { transliteration: 'Yasin', translation: 'Yasin' },
	37: { transliteration: 'As Saffat', translation: 'Yang Bersaf-Saf' },
	38: { transliteration: 'Sad', translation: 'Sad' },
	39: { transliteration: 'Az Zumar', translation: 'Rombongan' },
	40: { transliteration: 'Gafir', translation: 'Yang Maha Pengampun' },
	41: { transliteration: 'Fussilat', translation: 'Dijelaskan' },
	42: { transliteration: 'Asy Syura', translation: 'Musyawarah' },
	43: { transliteration: 'Az Zukhruf', translation: 'Perhiasan' },
	44: { transliteration: 'Ad Dukhan', translation: 'Kabut' },
	45: { transliteration: 'Al Jasiyah', translation: 'Yang Berlutut' },
	46: { transliteration: 'Al Ahqaf', translation: 'Bukit-Bukit Pasir' },
	47: { transliteration: 'Muhammad', translation: 'Muhammad' },
	48: { transliteration: 'Al Fath', translation: 'Kemenangan' },
	49: { transliteration: 'Al Hujurat', translation: 'Kamar-Kamar' },
	50: { transliteration: 'Qaf', translation: 'Qaf' },
	51: { transliteration: 'Az Zariyat', translation: 'Angin yang Menerbangkan' },
	52: { transliteration: 'At Tur', translation: 'Bukit' },
	53: { transliteration: 'An Najm', translation: 'Bintang' },
	54: { transliteration: 'Al Qamar', translation: 'Bulan' },
	55: { transliteration: 'Ar Rahman', translation: 'Yang Maha Pengasih' },
	56: { transliteration: 'Al Waqiah', translation: 'Hari Kiamat' },
	57: { transliteration: 'Al Hadid', translation: 'Besi' },
	58: { transliteration: 'Al Mujadalah', translation: 'Perempuan yang Mengajukan Gugatan' },
	59: { transliteration: 'Al Hasyr', translation: 'Pengusiran' },
	60: { transliteration: 'Al Mumtahanah', translation: 'Perempuan yang Diuji' },
	61: { transliteration: 'As Saff', translation: 'Barisan' },
	62: { transliteration: 'Al Jumuah', translation: 'Hari Jumat' },
	63: { transliteration: 'Al Munafiqun', translation: 'Orang-Orang Munafik' },
	64: { transliteration: 'At Tagabun', translation: 'Pengungkapan Kesalahan' },
	65: { transliteration: 'At Talaq', translation: 'Talak' },
	66: { transliteration: 'At Tahrim', translation: 'Pengharaman' },
	67: { transliteration: 'Al Mulk', translation: 'Kerajaan' },
	68: { transliteration: 'Al Qalam', translation: 'Pena' },
	69: { transliteration: 'Al Haqqah', translation: 'Hari Kiamat' },
	70: { transliteration: 'Al Maarij', translation: 'Tempat-Tempat Naik' },
	71: { transliteration: 'Nuh', translation: 'Nuh' },
	72: { transliteration: 'Al Jinn', translation: 'Jin' },
	73: { transliteration: 'Al Muzzammil', translation: 'Orang yang Berselimut' },
	74: { transliteration: 'Al Muddassir', translation: 'Orang yang Berkemul' },
	75: { transliteration: 'Al Qiyamah', translation: 'Hari Kiamat' },
	76: { transliteration: 'Al Insan', translation: 'Manusia' },
	77: { transliteration: 'Al Mursalat', translation: 'Malaikat-Malaikat yang Diutus' },
	78: { transliteration: 'An Naba', translation: 'Berita Besar' },
	79: { transliteration: 'An Naziat', translation: 'Malaikat-Malaikat yang Mencabut' },
	80: { transliteration: 'Abasa', translation: 'Dia Bermuka Masam' },
	81: { transliteration: 'At Takwir', translation: 'Penggulungan' },
	82: { transliteration: 'Al Infitar', translation: 'Terbelah' },
	83: { transliteration: 'Al Mutaffifin', translation: 'Orang-Orang Curang' },
	84: { transliteration: 'Al Insyiqaq', translation: 'Terbelah' },
	85: { transliteration: 'Al Buruj', translation: 'Gugusan Bintang' },
	86: { transliteration: 'At Tariq', translation: 'Yang Datang di Malam Hari' },
	87: { transliteration: 'Al Ala', translation: 'Yang Mahatinggi' },
	88: { transliteration: 'Al Gasyiyah', translation: 'Hari Pembalasan' },
	89: { transliteration: 'Al Fajr', translation: 'Fajar' },
	90: { transliteration: 'Al Balad', translation: 'Negeri' },
	91: { transliteration: 'Asy Syams', translation: 'Matahari' },
	92: { transliteration: 'Al Lail', translation: 'Malam' },
	93: { transliteration: 'Ad Duha', translation: 'Waktu Duha' },
	94: { transliteration: 'Asy Syarh', translation: 'Lapang' },
	95: { transliteration: 'At Tin', translation: 'Buah Tin' },
	96: { transliteration: 'Al Alaq', translation: 'Segumpal Darah' },
	97: { transliteration: 'Al Qadr', translation: 'Kemuliaan' },
	98: { transliteration: 'Al Bayyinah', translation: 'Bukti Nyata' },
	99: { transliteration: 'Az Zalzalah', translation: 'Guncangan' },
	100: { transliteration: 'Al Adiyat', translation: 'Kuda Perang yang Berlari Kencang' },
	101: { transliteration: 'Al Qariah', translation: 'Hari Kiamat' },
	102: { transliteration: 'At Takasur', translation: 'Bermegah-Megahan' },
	103: { transliteration: 'Al Asr', translation: 'Masa' },
	104: { transliteration: 'Al Humazah', translation: 'Pengumpat' },
	105: { transliteration: 'Al Fil', translation: 'Gajah' },
	106: { transliteration: 'Quraisy', translation: 'Quraisy' },
	107: { transliteration: 'Al Maun', translation: 'Barang-Barang yang Berguna' },
	108: { transliteration: 'Al Kausar', translation: 'Nikmat yang Banyak' },
	109: { transliteration: 'Al Kafirun', translation: 'Orang-Orang Kafir' },
	110: { transliteration: 'An Nasr', translation: 'Pertolongan' },
	111: { transliteration: 'Al Lahab', translation: 'Gejolak Api' },
	112: { transliteration: 'Al Ikhlas', translation: 'Ikhlas' },
	113: { transliteration: 'Al Falaq', translation: 'Waktu Subuh' },
	114: { transliteration: 'An Nas', translation: 'Manusia' }
};

export function getChapterDisplayMeta(chapterId) {
	return {
		...quranMetaData[chapterId],
		...(chapterDisplayOverrides[chapterId] ?? {})
	};
}
